Add example
UniqueNetwork/evm-coder pull request #3
Opened 2023-04-04 06:21 UTC by bugrazoid

2023-04-04 09:25 UTC, CertainLach commented on README.md
>  You can now run the appropriate tests to generate the `sol` stub files using the script.
Надо бы только не .sol, а api
Стабы это полезно, однако их пока во фронтир даже не скормить

2023-04-04 09:33 UTC, CertainLach requested changes

2023-04-04 09:33 UTC, CertainLach commented on README.md
> +	fn safe_transfer_from_with_data(&mut self, from: Address, to: Address, token_id: U256, data: Bytes) -> Result<()> {
Селектор будет некорректный, сейф трансфер по спеке перегружен. Может убрать expect_selector из примера? Это не то, что нужно писать каждый раз при разработке контракта

2023-04-04 09:33 UTC, CertainLach commented on README.md
> +        from: Address,
Тоже съехала табуляция

2023-04-04 09:33 UTC, CertainLach commented on README.md
> +impl<T: Config> ContractHandle<T> {}
ContractHandle в этом примере не объявлен как generic, да и Config непонятно откуда

2023-04-04 09:35 UTC, bugrazoid commented on README.md
> +        from: Address,
Уже поправил

2023-04-04 09:38 UTC, bugrazoid commented on README.md
> +	fn safe_transfer_from_with_data(&mut self, from: Address, to: Address, token_id: U256, data: Bytes) -> Result<()> {
Не, тут я как раз хочу подсветить, что у нас есть защита от неправильной генерации селектора для стандартных интерфейсов

2023-04-04 09:51 UTC, CertainLach commented on README.md
> +	fn safe_transfer_from_with_data(&mut self, from: Address, to: Address, token_id: U256, data: Bytes) -> Result<()> {
Тогда наверное стоит упомянуть что оно опциональное, и самому считать его не нужно

2023-04-05 12:17 UTC, Fahrrader commented
Стоит добавить секции про "установку", обзор и использование, к примеру,

2023-04-05 12:36 UTC, CertainLach commented
Умтановку лучше через ceates.io делать, пакет там опубликован

2023-04-05 12:41 UTC, Fahrrader commented
То есть, следующая структура:

# evm-coder
Library for seamless calls...

### Overview
Что делает, помимо сказанного выше (полный список возможностей), как делает (к примеру, кодирует в sol?), в бОльших подробностях, и где, в каких проектах он может быть нужен, в том числе.

### Usage
... To represent a contract in Substrate, implement or use the derive macro of the following trait on your struct depicting your contact [a bit of code] ...

### Installation
To add evm-coder to your project, add the following line to your Cargo.toml file...

### Example
For a sample project and a detailed tutorial, visit the examples [link] folder.

### License
...

2023-04-05 12:46 UTC, Fahrrader commented on README.md
> +It's so easy to maintain your types with the `AbiCoder` derived macro.
"Buy it now, just call this number!.."

Немножко смешно и по-продавщически звучит)

Не страшно, можно оставить так.

2023-04-05 12:52 UTC, bugrazoid commented on README.md
> +It's so easy to maintain your types with the `AbiCoder` derived macro.
Ну в этом и был смысл :)

2023-04-05 13:03 UTC, bugrazoid commented on README.md
> +	fn safe_transfer_from_with_data(&mut self, from: Address, to: Address, token_id: U256, data: Bytes) -> Result<()> {
Я думаю это будет понятно из реализации MyContract, где этот параметр отсутствует.

2023-04-06 12:16 UTC, CertainLach requested changes

2023-04-06 12:16 UTC, CertainLach commented on README.md
> +Let's create our extension:
Мне непонятно почему это вдруг extension. Ты имел в виду overloading?

2023-04-06 14:31 UTC, bugrazoid commented on README.md
> +As a result, we get the following `sol` stub file:
Да, согласен, поправлю

2023-04-06 14:33 UTC, bugrazoid commented on README.md
> +Let's create our extension:
Под расширением я тут имел ввиду пользовательский контракт.

2023-04-06 14:40 UTC, CertainLach commented on README.md
> +There is also support for function overloading using the macro `#[solidity(rename="funcName")]`.
Также про #[solidity_interface] - я бы его тоже назвал атрибутом
Макрос - деталь реализации, пускай пользовательские атрибуты сейчас и могут быть только макросами (Вообще, в rustc есть система плагинов, и атрибуты могут быть объявлены плагинами, просто у неё пользователи - firefox и servo). Для пользователя это просто атрибут.

2023-04-07 10:08 UTC, CertainLach requested changes

2023-04-07 10:26 UTC, Fahrrader commented on README.md
> +solidity interfaces for ethereum developers.
Solidity и Ethereum, желательно, с большой буквы

2023-04-07 10:27 UTC, Fahrrader commented on README.md
> +There is also support for function overloading using the atribute `#[solidity(rename="funcName")]`.
Нужна ещё одна пустая строка. Два абзаца сейчас отображаются как один.

2023-04-07 13:10 UTC, merged

2023-04-07 13:16 UTC, CertainLach commented on README.md
> +Add to `Cargo.toml` following lines:
Вообще, в cargo стабилизировали команду cargo add, лучше через неё)