Add support for bondrewd flags
UniqueNetwork/evm-coder pull request #7
Opened 2023-08-09 07:56 UTC by fairax

2023-08-09 08:33 UTC, CertainLach reviewed
Уфф, ты решил весь парсинг атрибутов из bondrewd взять...
Я то предлагал поддерживать минимум и сосредоточиться на том, как оно у нас реализовано будет
В таком случае мне надо проверить что наша кодогенерация адекватна оригинальному bondrewd

2023-08-09 08:33 UTC, CertainLach commented on procedural/src/abi_derive/derive_flags.rs
> +			const SIGNATURE: ::evm_coder::custom_signature::SignatureUnit = <(u32) as ::evm_coder::abi::AbiType>::SIGNATURE;
Тип нужно использовать из атрибута bondrewd, флаги коллекции в частности это u8

2023-08-09 08:33 UTC, CertainLach commented on procedural/src/abi_derive/derive_flags.rs
> +				let value = reader.uint32()?.to_le_bytes();
Нужно смотреть le/be ли у структуры
Сейчас при указании le тут, и be у структуры флаги будут развёрнуты

2023-08-09 08:51 UTC, CertainLach commented on procedural/src/abi_derive/derive_flags.rs
> +				write!(writer, "{}(0)", tc.collect_struct::<Self>())
```suggestion
				write!(writer, "{}.wrap(0)", tc.collect_struct::<Self>())
```
?

2023-08-09 08:58 UTC, CertainLach commented on procedural/src/abi_derive/derive_flags.rs
> +		let value = apply_le_math_to_mask(f);
Если поддерживать весь bondrewd, тогда предлагаю разделить однобитную и многобитную маску

Для однобитной стоит генерировать

Name constant foreign = 1 << bit_index

Для многобитной

function reserved(uint value) public view returns Name {
    require(value < 1 << (max_bits - bit_index), "out of bound value");
    Name.wrap(value << bit_index)
}

Иначе многобитные значения не имеют смысла

2023-08-09 11:58 UTC, fairax commented on procedural/src/abi_derive/derive_flags.rs
> +			const SIGNATURE: ::evm_coder::custom_signature::SignatureUnit = <(u32) as ::evm_coder::abi::AbiType>::SIGNATURE;
Вместо `u32`? Это же тип в котором хранятся все флаги вместе, а не отдельные поля. Для всей структуру в bondrewd тип не задаётся, только количество байт.

2023-08-09 15:42 UTC, CertainLach commented on procedural/src/abi_derive/derive_flags.rs
> +			const SIGNATURE: ::evm_coder::custom_signature::SignatureUnit = <(u32) as ::evm_coder::abi::AbiType>::SIGNATURE;
Задаётся количество байт, однако из этого количества байт выводится тип:
u8 - 0..=8 бит
u16 - 9..=16 бит
u32 - 17..=32 бита

Впрочем, можно не заморачиваться, и указать тут U256 (У нас всё равно все числа в evm выровнены по 32 байта, разницы нет)

2023-08-09 17:50 UTC, fairax commented on procedural/src/abi_derive/derive_flags.rs
> +			const SIGNATURE: ::evm_coder::custom_signature::SignatureUnit = <(u32) as ::evm_coder::abi::AbiType>::SIGNATURE;
Вместо u32? Это же тип в котором хранятся все флаги вместе, а не отдельные поля. Для всей структуру в bondrewd тип не задаётся, только количество байт.

2023-08-10 14:39 UTC, CertainLach requested changes

2023-08-10 14:39 UTC, CertainLach commented on procedural/src/abi_derive/derive_flags.rs
>  				Ok(#name::from_bytes([#(#bytes),*]))
Почти
bytes_padleft вернёт значение в big-endian
Однако у структуры может быть прописан LE, и в этом случае оно перевернёт флаги

Тут нужно в случае если у структуры прописан LE развернуть байты значения

2023-08-10 14:39 UTC, CertainLach commented on procedural/src/abi_derive/derive_flags.rs
> +	}
Хм, а почему?
lsb0 наоборот логичнее чаще использовать
```
3 = 0b0000011
            ^ lsb0
3 = 0b1100000
      ^ msb0
```

2023-08-10 14:39 UTC, CertainLach commented on procedural/src/abi_derive/derive_flags.rs
>  				Ok(#name::from_bytes([#(#bytes),*]))
`default_endianness = "native"` предлагаю явным образом запретить

2023-08-10 14:39 UTC, CertainLach commented on src/abi/mod.rs
> +	pub fn bytes_padleft<const S: usize>(&mut self) -> Result<[u8; S]> {
Добавь тут assert!(S <= ABI_ALIGNMENT);

2023-08-10 14:44 UTC, CertainLach commented on procedural/src/abi_derive/derive_flags.rs
> +				let value = reader.uint32()?.to_le_bytes();
По идее не должно работать

Попробуй на таком примере:
```rust
#[derive(AbiCoderFlags)]
#[bondrewd(default_endianness = "le")]
struct Data {
#[bondrewd(bits = "0..8")]
a: u8,
#[bondrewd(bits = "8..16")]
b: u8,
}

solidity_call(0x0100)
```
Байты вызова будут декодированы как `01 00` (padleft - BE)
`from_bytes` при LE декодирует 01 как поле `b`, а не как поле `a`

2023-08-10 17:46 UTC, fairax commented on procedural/src/abi_derive/derive_flags.rs
>  				Ok(#name::from_bytes([#(#bytes),*]))
Я тестировал с разным endianness, все вроде работает.

2023-08-10 17:48 UTC, fairax commented on procedural/src/abi_derive/derive_flags.rs
> +	}
Ну сейчас работает так, что если берёшь число, сдвигаешь его на нужное количество бит и добавляешь через OR к флагам, то всё десериализуется как надою. Если сделать lsb0, то десериализуется неправильсно..

2023-08-10 17:50 UTC, CertainLach commented on procedural/src/abi_derive/derive_flags.rs
>  				Ok(#name::from_bytes([#(#bytes),*]))
У тебя несколько байт было, или один?
Могу контрпример набросать, оно не должно работать без дополнительной конвертации

2023-08-10 21:30 UTC, fairax commented on procedural/src/abi_derive/derive_flags.rs
>  				Ok(#name::from_bytes([#(#bytes),*]))
Добавил тесты

2023-08-10 22:20 UTC, CertainLach commented on tests/abi_derive_generation.rs
> +		#[bondrewd(bits = "2..7", endianness = "le")]
endianness не имеет смысла в пределах одного байта
LE/BE это про кодирование чисел в несколько байт
Число 43981 = 0xabcd кодируется
В LE как `CD AB` (Расширение идёт вправо)
В BE как `AB CD` (Расширение идёт влево)

В нашем случае если пользователь указал структуре LE (этот атрибут ничего не делает на полях), то перед вызовом `from_bytes` нужно развернуть порядок байт

2023-08-10 22:21 UTC, CertainLach commented on tests/abi_derive_generation.rs
> +		#[bondrewd(bits = "2..7", endianness = "le")]
lsb0/msb0 - про другое, при lsb0 нужно разворачивать порядок битов внутри байта

2023-08-11 06:29 UTC, fairax commented on procedural/src/abi_derive/derive_flags.rs
> +				let value = reader.uint32()?.to_le_bytes();
Проверил, декодируется одинаково с LE и BE. Я так понимаю `default_endianness` это `endianness` для отедльных полей.

2023-08-11 06:30 UTC, fairax commented on procedural/src/abi_derive/derive_flags.rs
>  				Ok(#name::from_bytes([#(#bytes),*]))
>У тебя несколько байт было, или один?
См. выше.

2023-08-11 06:35 UTC, fairax commented on procedural/src/abi_derive/derive_flags.rs
> +	}
>Впрочем, если по дефолту там msb0 - то пусть

Да, по деволту msb0.

> Не, я понимаю, чтобы такого не было нужно разворачивать маски внутри битов

Да, и мне кажется это всё слишком усложняет с точки зрения пользователя.

2023-08-11 08:01 UTC, CertainLach commented on procedural/src/abi_derive/derive_flags.rs
> +	}
Пользователю ничего не нужно делать, это тебе перед from_bytes нужно каждый байт перевернуть

2023-08-14 08:17 UTC, CertainLach commented on procedural/src/abi_derive/derive_flags.rs
> +		.filter(|field| field.bit_size() > 8 && *field.attrs.endianness != Endianness::Big)
А default_endiannes поддерживается?

2023-08-14 08:18 UTC, CertainLach commented
Поддержку LE/lsb0 отложили, иные конфигурации пока запретили.

2023-08-14 08:33 UTC, fairax commented on procedural/src/abi_derive/derive_flags.rs
> +		.filter(|field| field.bit_size() > 8 && *field.attrs.endianness != Endianness::Big)
Она превращается в endianness полей и соответственно проверяется этой проверкой.

2023-08-14 09:01 UTC, merged

2023-08-14 09:03 UTC, CertainLach commented
Релиз 0.3.6 сейчас сделаю